### ISSUE TITLE
Lacked of bootstrapping 

### ISSUE THREAD

**Issue by aadiiver** [aadiiver/Hakons20#5]
Add bootstrap in the front-end for making it more compatible with the mobiles and tablets.

**Comment by ajayAlways** [comment]
can you assign me this?

**Comment by aadiiver** [comment]
Sure

**Comment by ajayAlways** [comment]
can you just elaborate what changes should I do?
Can I change CSS files for better front end appearance?

**Comment by aadiiver** [comment]
Yeah, you can change for better appearance and also add bootstrapping for mobile and tablet view experience.

**Comment by ajayAlways** [comment]
![Screenshot (161)](https://user-images.githubusercontent.com/54075270/103880558-4c2f8f80-50ff-11eb-81e7-5b2a4c5b502e.png)
![Screenshot (162)](https://user-images.githubusercontent.com/54075270/103880672-6e291200-50ff-11eb-8f7a-30f35472b5d5.png)
![Screenshot (160)](https://user-images.githubusercontent.com/54075270/103880915-bfd19c80-50ff-11eb-9ed6-e52498dbf966.png)

Is this enough? only options and login files are to be changed?

**Comment by aadiiver** [comment]
Yes, it is good.
